feat(feature): add release sub command
Add sub command to git flow feature that allows for a release to be
created based off the current feature branch. When running feature
release the feature branch is rebased with develop prior to the creation
of the release branch. When finishing the release the resulting tag is
back merged to the feature branch and not onto the production or develop
branches.

resolves #63

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -452,16 +452,12 @@ h,help!                Show this help
 	    gitflow_use_current_branch_name
 	fi
 
-	# 2) merge feature to dev
-	cmd_finish "--fetch" "--squash" "--keep"  $NAME
+	# 2) Update feature with dev
+	echo "Rebasing $BASE_BRANCH to $BRANCH"
+	git_do flow feature rebase || die "Could not rebase $BRANCH which is based on $BASE_BRANCH"
 
-	# 3) sync back dev to feature
-	echo "Merging $BASE_BRANCH to $BRANCH"
-	git_do checkout "$BRANCH" || die "Could not check out branch '$BRANCH'."
-	git_do merge "$BASE_BRANCH"
-
-	# 4) create release
-	git_do flow release start $NAME
+	# 3) create release
+	git_do flow release start $NAME $BRANCH
 
 }
 
